const CONFIG={apiUrl:localStorage.getItem('eightApiUrl')||'https://script.google.com/macros/s/AKfycbwj-jLaSTiljcw15_UnhUFv4QxVq5HbNyers3ybU-6IAkwSj_A5X36x-852Xu5MxobS/exec',businessStart:localStorage.getItem('eightBusinessStart')||'16:00',businessEnd:localStorage.getItem('eightBusinessEnd')||'07:00'};
let MEMBER_ROWS=[];let MEMBER_PAGE=1;const MEMBER_PAGE_SIZE=100;let MEMBER_SEARCH_TIMER=null;
const pages={dashboard:'總覽',members:'會員資料',events:'賽事管理',settlement:'分帳報表',accounting:'帳務管理',activities:'活動專區',devices:'設備管理',settings:'系統設定'};
const pad=n=>String(n).padStart(2,'0'),money=n=>new Intl.NumberFormat('zh-TW').format(Number(n||0));
function localISO(d){return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())}
function businessDate(now=new Date(),start=CONFIG.businessStart,end=CONFIG.businessEnd){const [sh,sm]=start.split(':').map(Number),[eh,em]=end.split(':').map(Number),mins=now.getHours()*60+now.getMinutes(),s=sh*60+sm,e=eh*60+em,d=new Date(now);if(e<s&&mins<e)d.setDate(d.getDate()-1);return localISO(d)}
async function api(action,payload={}){if(!CONFIG.apiUrl)throw new Error('API_NOT_CONFIGURED');const r=await fetch(CONFIG.apiUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...payload})});const j=await r.json();if(!j.ok)throw new Error(j.error||'API_ERROR');return j}
function setSync(t,bad=false){const e=document.querySelector('#syncState');e.textContent=t;e.style.color=bad?'var(--bad)':''}
function refreshBusinessDay(){CONFIG.businessStart=document.querySelector('#businessStart')?.value||CONFIG.businessStart;CONFIG.businessEnd=document.querySelector('#businessEnd')?.value||CONFIG.businessEnd;const d=businessDate();document.querySelector('#businessDayLabel').textContent='營業時間：每日 '+CONFIG.businessStart+'–翌日 '+CONFIG.businessEnd;document.querySelector('#todayDate').textContent=d;document.querySelector('#globalDate').value=d}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function memberSearchText(v){return String(v??'').normalize('NFKC').toLowerCase().replace(/\s+/g,'')}
function renderMembers(rows=MEMBER_ROWS){const q=memberSearchText(document.querySelector('#memberSearch')?.value||'');const filtered=q?rows.filter(m=>[m.memberId,m.name,m.nickname,m.group,m.phone].some(v=>memberSearchText(v).includes(q))):rows;const pages=Math.max(1,Math.ceil(filtered.length/MEMBER_PAGE_SIZE));MEMBER_PAGE=Math.min(MEMBER_PAGE,pages);const start=(MEMBER_PAGE-1)*MEMBER_PAGE_SIZE,list=filtered.slice(start,start+MEMBER_PAGE_SIZE);const tb=document.querySelector('#members tbody');const info=document.querySelector('#memberResultInfo');if(info)info.textContent='共 '+filtered.length+' 筆 · 第 '+MEMBER_PAGE+' / '+pages+' 頁';if(!list.length){tb.innerHTML='<tr><td colspan="10" class="empty">目前沒有符合的會員資料</td></tr>';return}tb.innerHTML=list.map(m=>'<tr data-key="'+esc(m.memberKey)+'"><td>'+esc(m.memberId)+'</td><td>'+esc(m.name)+'</td><td>'+esc(m.nickname)+'</td><td>'+esc(m.group)+'</td><td>'+money(m.eventCount)+'</td><td>'+money(m.totalEntries)+'</td><td>'+money(m.pnl)+'</td><td>'+esc(m.spendShare||'—')+'</td><td>'+esc(m.lastVisit||'—')+'</td><td class="row-actions"><button class="edit-member" data-key="'+esc(m.memberKey)+'">編輯</button><button class="delete-member danger" data-key="'+esc(m.memberKey)+'">刪除</button></td></tr>').join('');document.querySelector('#memberPrev').disabled=MEMBER_PAGE<=1;document.querySelector('#memberNext').disabled=MEMBER_PAGE>=pages}
function nextMemberId(){const used=new Set(MEMBER_ROWS.map(m=>String(m.memberId||'').trim().toUpperCase()));for(let i=0;i<100;i++){const id='A'+String(Math.floor(Math.random()*100000)).padStart(5,'0');if(!used.has(id))return id}return 'A'+String(Date.now()).slice(-5)}
function openMemberModal(member=null){document.querySelector('#memberForm').reset();document.querySelector('#memberKey').value=member?.memberKey||'';document.querySelector('#memberId').value=member?.memberId||nextMemberId();document.querySelector('#memberName').value=member?.name||'';document.querySelector('#memberNickname').value=member?.nickname||'';document.querySelector('#memberGroup').value=member?.group||'';document.querySelector('#memberBirth').value=member?.birth||'';document.querySelector('#memberPhone').value=member?.phone||'';document.querySelector('#memberAddress').value=member?.address||'';document.querySelector('#memberModalTitle').textContent=member?'編輯會員':'新增會員';document.querySelector('#memberFormState').textContent='';document.querySelector('#memberFormState').className='form-state';document.querySelector('#memberModal').hidden=false}
function closeMemberModal(){document.querySelector('#memberModal').hidden=true}
async function saveMember(e){e.preventDefault();const btn=document.querySelector('#memberSaveBtn'),state=document.querySelector('#memberFormState'),memberKey=document.querySelector('#memberKey').value;const data={memberId:document.querySelector('#memberId').value.trim(),name:document.querySelector('#memberName').value.trim(),nickname:document.querySelector('#memberNickname').value.trim(),group:document.querySelector('#memberGroup').value.trim(),birth:document.querySelector('#memberBirth').value.trim(),phone:document.querySelector('#memberPhone').value.trim(),address:document.querySelector('#memberAddress').value.trim()};if(memberKey){const original=MEMBER_ROWS.find(x=>x.memberKey===memberKey);['birth','phone','address'].forEach(k=>{if(original&&original[k]===undefined)delete data[k]})}if(!data.memberId||!data.name){state.textContent='POKER FANS ID 與姓名為必填';state.className='form-state bad';return}btn.disabled=true;state.textContent='儲存中…';try{if(memberKey)await api('eight.members.update',{memberKey,patch:data});else await api('eight.members.create',{member:data});state.textContent='儲存成功';state.className='form-state good';await boot();setTimeout(closeMemberModal,350)}catch(err){console.error(err);const msg={MEMBER_ID_ALREADY_EXISTS:'POKER FANS ID 已存在',MEMBER_ID_REQUIRED:'POKER FANS ID 為必填',MEMBER_NAME_REQUIRED:'姓名為必填',MEMBER_NOT_FOUND:'找不到此會員'}[err.message]||err.message;state.textContent='儲存失敗：'+msg;state.className='form-state bad'}finally{btn.disabled=false}}
async function boot(){refreshBusinessDay();if(!CONFIG.apiUrl){setSync('資料庫：等待 Apps Script 部署');return}try{setSync('資料庫：同步中…');const r=await api('eight.bootstrap');if(r.settings){CONFIG.businessStart=r.settings.businessStart||CONFIG.businessStart;CONFIG.businessEnd=r.settings.businessEnd||CONFIG.businessEnd;document.querySelector('#businessStart').value=CONFIG.businessStart;document.querySelector('#businessEnd').value=CONFIG.businessEnd}MEMBER_ROWS=r.members||[];renderMembers();document.querySelector('#kMembers').textContent=money(r.summary?.memberCount);document.querySelector('#kNewMembers').textContent=money(r.summary?.monthNewMembers);refreshBusinessDay();setSync('資料庫：已連線')}catch(e){console.error(e);setSync('資料庫：連線失敗',true)}}
document.querySelectorAll('#nav button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#'+b.dataset.page).classList.add('active');document.querySelector('#pageTitle').textContent=pages[b.dataset.page]}));
document.querySelector('#themeBtn').addEventListener('click',()=>{const dark=document.body.dataset.theme==='dark';document.body.dataset.theme=dark?'light':'dark';document.querySelector('#themeBtn').textContent=dark?'☾ 深色模式':'☀ 一般模式';localStorage.setItem('eightTheme',document.body.dataset.theme)});
document.body.dataset.theme=localStorage.getItem('eightTheme')||'dark';
document.querySelector('#businessStart').addEventListener('change',refreshBusinessDay);document.querySelector('#businessEnd').addEventListener('change',refreshBusinessDay);
document.querySelector('#saveBusinessHours').addEventListener('click',async()=>{const state=document.querySelector('#businessSaveState');const start=document.querySelector('#businessStart').value,end=document.querySelector('#businessEnd').value;state.textContent='儲存中…';try{const r=await api('eight.settings.update',{settings:{businessStart:start,businessEnd:end}});CONFIG.businessStart=r.settings.businessStart;CONFIG.businessEnd=r.settings.businessEnd;localStorage.removeItem('eightBusinessStart');localStorage.removeItem('eightBusinessEnd');refreshBusinessDay();state.textContent='已同步到資料庫'}catch(err){state.textContent='儲存失敗：'+err.message}setTimeout(()=>state.textContent='',2200)});
const now=new Date(),first=new Date(now.getFullYear(),now.getMonth(),1);document.querySelector('#rangeFrom').value=localISO(first);document.querySelector('#rangeTo').value=localISO(now);
document.querySelector('#refreshBtn').addEventListener('click',boot);boot();
document.querySelector('#addMemberBtn').addEventListener('click',()=>openMemberModal());
document.querySelectorAll('[data-close-member]').forEach(x=>x.addEventListener('click',closeMemberModal));
document.querySelector('#memberForm').addEventListener('submit',saveMember);
document.querySelector('#memberSearch').addEventListener('input',()=>{clearTimeout(MEMBER_SEARCH_TIMER);MEMBER_SEARCH_TIMER=setTimeout(()=>{MEMBER_PAGE=1;renderMembers()},120)});
document.querySelector('#memberPrev').addEventListener('click',()=>{if(MEMBER_PAGE>1){MEMBER_PAGE--;renderMembers()}});
document.querySelector('#memberNext').addEventListener('click',()=>{MEMBER_PAGE++;renderMembers()});
document.querySelector('#members tbody').addEventListener('click',async e=>{const edit=e.target.closest('.edit-member');if(edit){const m=MEMBER_ROWS.find(x=>x.memberKey===edit.dataset.key);if(m)openMemberModal(m);return}const del=e.target.closest('.delete-member');if(!del)return;const m=MEMBER_ROWS.find(x=>x.memberKey===del.dataset.key);if(!m)return;if(!confirm('確定永久刪除會員「'+m.name+'」（'+m.memberId+'）？\n\n這會刪除會員主表與會員 META 資料。'))return;if(!confirm('再次確認：永久刪除後無法從會員頁復原。確定刪除？'))return;del.disabled=true;try{await api('eight.members.delete',{memberKey:m.memberKey});MEMBER_ROWS=MEMBER_ROWS.filter(x=>x.memberKey!==m.memberKey);renderMembers();document.querySelector('#kMembers').textContent=money(MEMBER_ROWS.filter(x=>x.status!=='inactive').length)}catch(err){const msg={MEMBER_SOURCE_DUPLICATE_ID:'此 POKER FANS ID 有重複資料，為避免刪錯已停止刪除',MEMBER_NOT_FOUND:'找不到此會員'}[err.message]||err.message;alert('刪除失敗：'+msg);del.disabled=false}});

const EVENT_PRESETS={3400:[3000,400],6600:[6000,600],11000:[10000,1000],21500:[20000,1500],32000:[30000,2000]};
function openEventModal(){document.querySelector('#eventForm').reset();const d=document.querySelector('#eventDate').value||businessDate();document.querySelector('#eventBusinessDate').value=d;document.querySelector('#eventLevel').value='3400';document.querySelector('#eventBuyin').value=3000;document.querySelector('#eventFee').value=400;document.querySelector('#eventJP').value=3;document.querySelector('#eventName').value='EPC#1 3400 限時錦標賽';document.querySelector('#eventFormState').textContent='';document.querySelector('#eventModal').hidden=false}
function closeEventModal(){document.querySelector('#eventModal').hidden=true}
document.querySelector('#eventDate').value=businessDate();
document.querySelector('#eventTodayBtn').addEventListener('click',()=>document.querySelector('#eventDate').value=businessDate());
document.querySelector('#createEventBtn').addEventListener('click',openEventModal);
document.querySelectorAll('[data-close-event]').forEach(x=>x.addEventListener('click',closeEventModal));
document.querySelector('#eventLevel').addEventListener('change',e=>{const p=EVENT_PRESETS[e.target.value];if(p){document.querySelector('#eventBuyin').value=p[0];document.querySelector('#eventFee').value=p[1]}const n=document.querySelector('#eventName');if(/^EPC#1\s/.test(n.value)||!n.value.trim())n.value='EPC#1 '+(e.target.value==='custom'?'自訂':e.target.value)+' 限時錦標賽'});
function renderEvents(rows=[]){window.EIGHT_EVENTS=rows;const el=document.querySelector('#eventList');if(!rows.length){el.className='empty';el.innerHTML='目前營業日尚無賽事';return}el.className='event-list';el.innerHTML=rows.map(x=>'<div class="event-row"><div><b>'+esc(x.name||'未命名賽事')+'</b><small>'+esc(x.businessDate||'')+' · '+esc(x.startTime||'')+' · '+esc(x.level||'自訂')+'</small></div><div><span>買入 '+money(x.buyin)+'</span><span>行政費 '+money(x.fee)+'</span><button class="secondary keyin-event" data-id="'+esc(x.eventId)+'">玩家 KEYIN</button><button class="danger delete-event" data-id="'+esc(x.eventId)+'">刪除</button></div></div>').join('')}
async function loadEvents(){try{const r=await api('eight.events.list',{businessDate:document.querySelector('#eventDate').value||businessDate()});renderEvents(r.events||[])}catch(err){if(err.message!=='UNKNOWN_ACTION')console.error(err)}}
document.querySelector('#eventDate').addEventListener('change',loadEvents);
document.querySelector('#eventForm').addEventListener('submit',async e=>{e.preventDefault();const state=document.querySelector('#eventFormState');let eventName=document.querySelector('#eventName').value.trim();if(!eventName)eventName='EPC#1 '+(document.querySelector('#eventLevel').value==='custom'?'自訂':document.querySelector('#eventLevel').value)+' 限時錦標賽';const event={name:eventName,businessDate:document.querySelector('#eventBusinessDate').value,startTime:document.querySelector('#eventStartTime').value,regClose:document.querySelector('#eventRegClose').value,level:document.querySelector('#eventLevel').value,buyin:Number(document.querySelector('#eventBuyin').value||0),fee:Number(document.querySelector('#eventFee').value||0),jpRate:Number(document.querySelector('#eventJP').value||0)};state.textContent='建立中…';try{await api('eight.events.create',{event});state.textContent='建立成功';state.className='form-state good';document.querySelector('#eventDate').value=event.businessDate;await loadEvents();setTimeout(closeEventModal,300)}catch(err){state.textContent='建立失敗：'+({UNKNOWN_ACTION:'後端賽事 API 尚未部署'}[err.message]||err.message);state.className='form-state bad'}});
let ACTIVE_EVENT=null,EVENT_PLAYERS=[];
function openPlayersModal(eventId){ACTIVE_EVENT=eventId;const ev=(window.EIGHT_EVENTS||[]).find(x=>x.eventId===eventId);document.querySelector('#eventPlayersTitle').textContent=ev?.name||'賽事玩家';document.querySelector('#eventPlayersMeta').textContent=(ev?.businessDate||'')+' '+(ev?.startTime||'');document.querySelector('#eventMemberSearch').value='';document.querySelector('#eventMemberMatches').innerHTML='';document.querySelector('#eventPlayersModal').hidden=false;loadEventPlayers()}
function closePlayersModal(){document.querySelector('#eventPlayersModal').hidden=true;ACTIVE_EVENT=null}
async function loadEventPlayers(){if(!ACTIVE_EVENT)return;try{const r=await api('eight.eventPlayers.list',{eventId:ACTIVE_EVENT});EVENT_PLAYERS=r.players||[];renderEventPlayers()}catch(err){EVENT_PLAYERS=[];renderEventPlayers()}}
function renderEventPlayers(){const el=document.querySelector('#eventPlayerList');document.querySelector('#eventPlayerCount').textContent=EVENT_PLAYERS.length+' 人';if(!EVENT_PLAYERS.length){el.className='empty';el.innerHTML='尚未加入玩家';return}el.className='player-list';el.innerHTML=EVENT_PLAYERS.map(p=>'<div class="player-row"><div><b>'+esc(p.name||'')+'</b><small>'+esc(p.memberId||'')+'</small></div><div><label>買入組數 <input class="entry-count" data-key="'+esc(p.memberKey)+'" type="number" min="1" value="'+esc(p.entries||1)+'"></label><button class="danger remove-player" data-key="'+esc(p.memberKey)+'">移除</button></div></div>').join('')}
document.querySelectorAll('[data-close-players]').forEach(x=>x.addEventListener('click',closePlayersModal));
document.querySelector('#eventMemberSearch').addEventListener('input',e=>{const q=memberSearchText(e.target.value);const box=document.querySelector('#eventMemberMatches');if(!q){box.innerHTML='';return}const joined=new Set(EVENT_PLAYERS.map(x=>x.memberKey));const list=MEMBER_ROWS.filter(m=>!joined.has(m.memberKey)&&[m.memberId,m.name,m.nickname].some(v=>memberSearchText(v).includes(q))).slice(0,8);box.innerHTML=list.map(m=>'<button type="button" class="member-match" data-key="'+esc(m.memberKey)+'"><b>'+esc(m.name)+'</b><small>'+esc(m.memberId)+(m.nickname?' · '+esc(m.nickname):'')+'</small></button>').join('')});
document.querySelector('#eventMemberMatches').addEventListener('click',async e=>{const b=e.target.closest('.member-match');if(!b||!ACTIVE_EVENT)return;b.disabled=true;try{await api('eight.eventPlayers.add',{eventId:ACTIVE_EVENT,memberKey:b.dataset.key});await loadEventPlayers();document.querySelector('#eventMemberSearch').value='';document.querySelector('#eventMemberMatches').innerHTML=''}catch(err){alert('加入失敗：'+err.message)}});
document.querySelector('#eventPlayerList').addEventListener('change',async e=>{const input=e.target.closest('.entry-count,.discount-amount,.settlement-group,.chip-count');if(!input||!ACTIVE_EVENT)return;let patch={};if(input.classList.contains('entry-count'))patch.entries=Number(input.value||1);if(input.classList.contains('discount-amount'))patch.discount=Number(input.value||0);if(input.classList.contains('settlement-group'))patch.group=input.value.trim();if(input.classList.contains('chip-count'))patch.chips=Number(input.value||0);try{await api('eight.eventPlayers.update',{eventId:ACTIVE_EVENT,memberKey:input.dataset.key,patch})}catch(err){alert('更新失敗：'+err.message);await loadEventPlayers()}});
document.querySelector('#eventPlayerList').addEventListener('click',async e=>{const b=e.target.closest('.remove-player');if(!b||!ACTIVE_EVENT)return;if(!confirm('確定將此玩家移出賽事？'))return;try{await api('eight.eventPlayers.delete',{eventId:ACTIVE_EVENT,memberKey:b.dataset.key});await loadEventPlayers()}catch(err){alert('移除失敗：'+err.message)}});
document.querySelector('#eventList').addEventListener('click',e=>{const b=e.target.closest('.keyin-event');if(b){openPlayersModal(b.dataset.id);return}});
document.querySelector('#eventList').addEventListener('click',async e=>{const p=e.target.closest('.event-players');if(p){openPlayersModal(p.dataset.id);return}const b=e.target.closest('.delete-event');if(!b)return;if(!confirm('確定刪除此賽事？'))return;try{await api('eight.events.delete',{eventId:b.dataset.id});await loadEvents()}catch(err){alert('刪除失敗：'+err.message)}});
loadEvents();
