const CONFIG={apiUrl:localStorage.getItem('eightApiUrl')||'https://script.google.com/macros/s/AKfycbwj-jLaSTiljcw15_UnhUFv4QxVq5HbNyers3ybU-6IAkwSj_A5X36x-852Xu5MxobS/exec',businessStart:localStorage.getItem('eightBusinessStart')||'16:00',businessEnd:localStorage.getItem('eightBusinessEnd')||'07:00'};
let MEMBER_ROWS=[];let MEMBER_PAGE=1;const MEMBER_PAGE_SIZE=100;let MEMBER_SEARCH_TIMER=null;
const pages={dashboard:'總覽',members:'會員資料',events:'賽事管理',settlement:'分帳報表',accounting:'帳務管理',activities:'活動專區',devices:'設備管理',settings:'系統設定'};
const pad=n=>String(n).padStart(2,'0'),money=n=>new Intl.NumberFormat('zh-TW').format(Number(n||0));
function localISO(d){return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())}
function businessDate(now=new Date(),start=CONFIG.businessStart,end=CONFIG.businessEnd){const [sh,sm]=start.split(':').map(Number),[eh,em]=end.split(':').map(Number),mins=now.getHours()*60+now.getMinutes(),s=sh*60+sm,e=eh*60+em,d=new Date(now);if(e<s&&mins<e)d.setDate(d.getDate()-1);return localISO(d)}
async function api(action,payload={}){if(!CONFIG.apiUrl)throw new Error('API_NOT_CONFIGURED');const r=await fetch(CONFIG.apiUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...payload})});const j=await r.json();if(!j.ok)throw new Error(j.error||'API_ERROR');return j}
function setSync(t,bad=false){const e=document.querySelector('#syncState');e.textContent=t;e.style.color=bad?'var(--bad)':''}
function refreshBusinessDay(){CONFIG.businessStart=document.querySelector('#businessStart')?.value||CONFIG.businessStart;CONFIG.businessEnd=document.querySelector('#businessEnd')?.value||CONFIG.businessEnd;const d=businessDate();document.querySelector('#businessDayLabel').textContent='營業時間：每日 '+CONFIG.businessStart+'–翌日 '+CONFIG.businessEnd;document.querySelector('#todayDate').textContent=d;document.querySelector('#globalDate').value=d}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function memberSearchText(v){return String(v??'').normalize('NFKC').toLowerCase().replace(/\s+/g,'')}
function renderMembers(rows=MEMBER_ROWS){const q=memberSearchText(document.querySelector('#memberSearch')?.value||'');const filtered=q?rows.filter(m=>[m.memberId,m.name,m.nickname,m.group,m.phone].some(v=>memberSearchText(v).includes(q))):rows;const pages=Math.max(1,Math.ceil(filtered.length/MEMBER_PAGE_SIZE));MEMBER_PAGE=Math.min(MEMBER_PAGE,pages);const start=(MEMBER_PAGE-1)*MEMBER_PAGE_SIZE,list=filtered.slice(start,start+MEMBER_PAGE_SIZE);const tb=document.querySelector('#members tbody');const info=document.querySelector('#memberResultInfo');if(info)info.textContent='共 '+filtered.length+' 筆 · 第 '+MEMBER_PAGE+' / '+pages+' 頁';if(!list.length){tb.innerHTML='<tr><td colspan="10" class="empty">目前沒有符合的會員資料</td></tr>';return}tb.innerHTML=list.map(m=>'<tr data-key="'+esc(m.memberKey)+'"><td>'+esc(m.memberId)+'</td><td>'+esc(m.name)+'</td><td>'+esc(m.nickname)+'</td><td>'+esc(m.group)+'</td><td>'+money(m.eventCount)+'</td><td>'+money(m.totalEntries)+'</td><td>'+money(m.pnl)+'</td><td>'+esc(m.spendShare||'—')+'</td><td>'+esc(m.lastVisit||'—')+'</td><td class="row-actions"><button class="edit-member" data-key="'+esc(m.memberKey)+'">編輯</button><button class="delete-member danger" data-key="'+esc(m.memberKey)+'">刪除</button></td></tr>').join('');document.querySelector('#memberPrev').disabled=MEMBER_PAGE<=1;document.querySelector('#memberNext').disabled=MEMBER_PAGE>=pages}
function nextMemberId(){let max=0;for(const m of MEMBER_ROWS){const s=String(m.memberId||'').trim();if(/^\d+$/.test(s))max=Math.max(max,Number(s))}return String(max+1)}
function openMemberModal(member=null){document.querySelector('#memberForm').reset();document.querySelector('#memberKey').value=member?.memberKey||'';document.querySelector('#memberId').value=member?.memberId||nextMemberId();document.querySelector('#memberName').value=member?.name||'';document.querySelector('#memberNickname').value=member?.nickname||'';document.querySelector('#memberGroup').value=member?.group||'';document.querySelector('#memberBirth').value=member?.birth||'';document.querySelector('#memberPhone').value=member?.phone||'';document.querySelector('#memberAddress').value=member?.address||'';document.querySelector('#memberModalTitle').textContent=member?'編輯會員':'新增會員';document.querySelector('#memberFormState').textContent='';document.querySelector('#memberFormState').className='form-state';document.querySelector('#memberModal').hidden=false}
function closeMemberModal(){document.querySelector('#memberModal').hidden=true}
async function saveMember(e){e.preventDefault();const btn=document.querySelector('#memberSaveBtn'),state=document.querySelector('#memberFormState'),memberKey=document.querySelector('#memberKey').value;const data={memberId:document.querySelector('#memberId').value.trim(),name:document.querySelector('#memberName').value.trim(),nickname:document.querySelector('#memberNickname').value.trim(),group:document.querySelector('#memberGroup').value.trim(),birth:document.querySelector('#memberBirth').value.trim(),phone:document.querySelector('#memberPhone').value.trim(),address:document.querySelector('#memberAddress').value.trim()};if(memberKey){const original=MEMBER_ROWS.find(x=>x.memberKey===memberKey);['birth','phone','address'].forEach(k=>{if(original&&original[k]===undefined)delete data[k]})}if(!data.memberId||!data.name){state.textContent='POKER FANS ID 與姓名為必填';state.className='form-state bad';return}btn.disabled=true;state.textContent='儲存中…';try{if(memberKey)await api('eight.members.update',{memberKey,patch:data});else await api('eight.members.create',{member:data});state.textContent='儲存成功';state.className='form-state good';await boot();setTimeout(closeMemberModal,350)}catch(err){console.error(err);const msg={MEMBER_ID_ALREADY_EXISTS:'POKER FANS ID 已存在',MEMBER_ID_REQUIRED:'POKER FANS ID 為必填',MEMBER_NAME_REQUIRED:'姓名為必填',MEMBER_NOT_FOUND:'找不到此會員'}[err.message]||err.message;state.textContent='儲存失敗：'+msg;state.className='form-state bad'}finally{btn.disabled=false}}
async function boot(){refreshBusinessDay();if(!CONFIG.apiUrl){setSync('資料庫：等待 Apps Script 部署');return}try{setSync('資料庫：同步中…');const r=await api('eight.bootstrap');if(r.settings){CONFIG.businessStart=localStorage.getItem('eightBusinessStart')||r.settings.businessStart||CONFIG.businessStart;CONFIG.businessEnd=localStorage.getItem('eightBusinessEnd')||r.settings.businessEnd||CONFIG.businessEnd;document.querySelector('#businessStart').value=CONFIG.businessStart;document.querySelector('#businessEnd').value=CONFIG.businessEnd}MEMBER_ROWS=r.members||[];renderMembers();document.querySelector('#kMembers').textContent=money(r.summary?.memberCount);document.querySelector('#kNewMembers').textContent=money(r.summary?.monthNewMembers);refreshBusinessDay();setSync('資料庫：已連線')}catch(e){console.error(e);setSync('資料庫：連線失敗',true)}}
document.querySelectorAll('#nav button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#'+b.dataset.page).classList.add('active');document.querySelector('#pageTitle').textContent=pages[b.dataset.page]}));
document.querySelector('#themeBtn').addEventListener('click',()=>{const dark=document.body.dataset.theme==='dark';document.body.dataset.theme=dark?'light':'dark';document.querySelector('#themeBtn').textContent=dark?'☾ 深色模式':'☀ 一般模式';localStorage.setItem('eightTheme',document.body.dataset.theme)});
document.body.dataset.theme=localStorage.getItem('eightTheme')||'dark';
document.querySelector('#businessStart').addEventListener('change',refreshBusinessDay);document.querySelector('#businessEnd').addEventListener('change',refreshBusinessDay);
document.querySelector('#saveBusinessHours').addEventListener('click',()=>{CONFIG.businessStart=document.querySelector('#businessStart').value;CONFIG.businessEnd=document.querySelector('#businessEnd').value;localStorage.setItem('eightBusinessStart',CONFIG.businessStart);localStorage.setItem('eightBusinessEnd',CONFIG.businessEnd);refreshBusinessDay();document.querySelector('#businessSaveState').textContent='已儲存';setTimeout(()=>document.querySelector('#businessSaveState').textContent='',1800)});
const now=new Date(),first=new Date(now.getFullYear(),now.getMonth(),1);document.querySelector('#rangeFrom').value=localISO(first);document.querySelector('#rangeTo').value=localISO(now);
document.querySelector('#refreshBtn').addEventListener('click',boot);boot();
document.querySelector('#addMemberBtn').addEventListener('click',()=>openMemberModal());
document.querySelectorAll('[data-close-member]').forEach(x=>x.addEventListener('click',closeMemberModal));
document.querySelector('#memberForm').addEventListener('submit',saveMember);
document.querySelector('#memberSearch').addEventListener('input',()=>{clearTimeout(MEMBER_SEARCH_TIMER);MEMBER_SEARCH_TIMER=setTimeout(()=>{MEMBER_PAGE=1;renderMembers()},120)});
document.querySelector('#memberPrev').addEventListener('click',()=>{if(MEMBER_PAGE>1){MEMBER_PAGE--;renderMembers()}});
document.querySelector('#memberNext').addEventListener('click',()=>{MEMBER_PAGE++;renderMembers()});
document.querySelector('#members tbody').addEventListener('click',async e=>{const edit=e.target.closest('.edit-member');if(edit){const m=MEMBER_ROWS.find(x=>x.memberKey===edit.dataset.key);if(m)openMemberModal(m);return}const del=e.target.closest('.delete-member');if(!del)return;const m=MEMBER_ROWS.find(x=>x.memberKey===del.dataset.key);if(!m)return;if(!confirm('確定永久刪除會員「'+m.name+'」（'+m.memberId+'）？\n\n這會刪除會員主表與會員 META 資料。'))return;if(!confirm('再次確認：永久刪除後無法從會員頁復原。確定刪除？'))return;del.disabled=true;try{await api('eight.members.delete',{memberKey:m.memberKey});MEMBER_ROWS=MEMBER_ROWS.filter(x=>x.memberKey!==m.memberKey);renderMembers();document.querySelector('#kMembers').textContent=money(MEMBER_ROWS.filter(x=>x.status!=='inactive').length)}catch(err){const msg={MEMBER_SOURCE_DUPLICATE_ID:'此 POKER FANS ID 有重複資料，為避免刪錯已停止刪除',MEMBER_NOT_FOUND:'找不到此會員'}[err.message]||err.message;alert('刪除失敗：'+msg);del.disabled=false}});
